export the variables to a file i'm guessing we'll need to do this for the circle token, too

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -31,6 +31,10 @@ jobs:
             fi
             echo "export VAULT_TOKEN=$VAULT_TOKEN" >> $BASH_ENV
             echo "export PRODUCTION_VAULT_TOKEN=$VAULT_TOKEN" >> $BASH_ENV
+            touch secrets-env && chmod 600 secrets-env
+            echo export VAULT_TOKEN=\"${VAULT_TOKEN}\"" >> secrets-env
+            echo export VAULT_ADDR=\"${VAULT_ADDR}\"" >> secrets-env
+            echo export VAULT_CACERT=\"${VAULT_CACERT}\"" >> secrets-env
       - run:
           name: "Export GitHub Token from Vault"
           command: |
@@ -39,6 +43,13 @@ jobs:
             if [ $? -ne 0 ]; then
               echo "Vault not found...weird... 🤔"
               exit 1
+            fi
+            # Make sure we have secrets-env.
+            if [ ! -f secrets-env ]; then
+              echo "Could not find secrets-env! 😱 Exiting..."
+              exit 1
+            else
+              . secrets-env
             fi
             CIRCLE_GH_TOKEN=$(vault read -field=token secret/github/access-tokens/pantheon-ci-bot)
             if [ -z "$CIRCLE_GH_TOKEN" ]; then
